/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NewJFrame;

/**
 *
 * @author acer
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    double num1,num2=0;
    String show,op;
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tresult = new javax.swing.JTextField();
        bbtn0 = new javax.swing.JButton();
        bbtn7 = new javax.swing.JButton();
        bbtn4 = new javax.swing.JButton();
        bbtn5 = new javax.swing.JButton();
        bbtn2 = new javax.swing.JButton();
        bbtnsign = new javax.swing.JButton();
        bbtn6 = new javax.swing.JButton();
        bbtn3 = new javax.swing.JButton();
        bbtn8 = new javax.swing.JButton();
        bbtn9 = new javax.swing.JButton();
        bbtnplus = new javax.swing.JButton();
        bbtnmultiply = new javax.swing.JButton();
        bbtnminus = new javax.swing.JButton();
        bbtndivide = new javax.swing.JButton();
        bbtnequal = new javax.swing.JButton();
        bbtnclear = new javax.swing.JButton();
        btnbs = new javax.swing.JButton();
        bbtndot = new javax.swing.JButton();
        bbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tresult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tresult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tresult.setToolTipText("");
        getContentPane().add(tresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, 80));

        bbtn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn0.setText("0");
        bbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, 60));

        bbtn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn7.setText("7");
        bbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 60, 60));

        bbtn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn4.setText("4");
        bbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 60));

        bbtn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn5.setText("5");
        bbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 60, 60));

        bbtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn2.setText("2");
        bbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 60, 60));

        bbtnsign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bbtnsign.setText("+/-");
        bbtnsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnsignActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 60, 60));

        bbtn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn6.setText("6");
        bbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 60, 60));

        bbtn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn3.setText("3");
        bbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 60, 60));

        bbtn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn8.setText("8");
        bbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, 60));

        bbtn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn9.setText("9");
        bbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 60, 60));

        bbtnplus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtnplus.setText("+");
        bbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 80, 60));

        bbtnmultiply.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtnmultiply.setText("x");
        bbtnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnmultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnmultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 60));

        bbtnminus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtnminus.setText("-");
        bbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnminusActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 80, 60));

        bbtndivide.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtndivide.setText("/");
        bbtndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtndivideActionPerformed(evt);
            }
        });
        getContentPane().add(bbtndivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, 60));

        bbtnequal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtnequal.setText("=");
        bbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnequalActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 170, 60));

        bbtnclear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtnclear.setText("C");
        bbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnclearActionPerformed(evt);
            }
        });
        getContentPane().add(bbtnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 80, 60));

        btnbs.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnbs.setText("<");
        btnbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbsActionPerformed(evt);
            }
        });
        getContentPane().add(btnbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, 60));

        bbtndot.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bbtndot.setText(".");
        bbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtndotActionPerformed(evt);
            }
        });
        getContentPane().add(bbtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, 60));

        bbtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bbtn1.setText("1");
        bbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(bbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enteredval(String q)
    {
        String num = tresult.getText() + q;
        tresult.setText(num);
    }
    
    private void bbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn0ActionPerformed
        enteredval("0");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn0ActionPerformed

    private void bbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnmultiplyActionPerformed
        num1 = Double.parseDouble(tresult.getText());
        tresult.setText(null);
        op = "*";
    }//GEN-LAST:event_bbtnmultiplyActionPerformed

    private void bbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnminusActionPerformed
        num1 = Double.parseDouble(tresult.getText());
        tresult.setText(null);
        op = "-";
    }//GEN-LAST:event_bbtnminusActionPerformed

    private void bbtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtndivideActionPerformed
        num1 = Double.parseDouble(tresult.getText());
        tresult.setText(null);
        op = "/";
    }//GEN-LAST:event_bbtndivideActionPerformed

    private void bbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnequalActionPerformed
        num2 = Double.parseDouble(tresult.getText());
        switch (op) {
            case "*" -> show = (num1*num2) + "";
            case "/" -> show = (num1/num2) + "";
            case "+" -> show = (num1+num2) + "";
            case "-" -> show = (num1-num2) + "";
            default -> {
            }
        }
        tresult.setText(show);
    }//GEN-LAST:event_bbtnequalActionPerformed

    private void bbtnsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnsignActionPerformed
        num1 = Double.parseDouble(tresult.getText());
        show = (num1 * (-1)) + "";
        tresult.setText(show);// TODO add your handling code here:
    }//GEN-LAST:event_bbtnsignActionPerformed

    private void bbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn7ActionPerformed
       enteredval("7");
        // TODO add your handling code here:
    }//GEN-LAST:event_bbtn7ActionPerformed

    private void bbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn8ActionPerformed
        enteredval("8");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn8ActionPerformed

    private void bbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn9ActionPerformed
        enteredval("9");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn9ActionPerformed

    private void bbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn2ActionPerformed
        enteredval("2");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn2ActionPerformed

    private void bbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn3ActionPerformed
        enteredval("3");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn3ActionPerformed

    private void bbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn4ActionPerformed
        enteredval("4");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn4ActionPerformed

    private void bbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn5ActionPerformed
        enteredval("5");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn5ActionPerformed

    private void bbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn6ActionPerformed
        enteredval("6");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn6ActionPerformed

    private void bbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnclearActionPerformed
        tresult.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_bbtnclearActionPerformed

    private void btnbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbsActionPerformed

        if(tresult.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(tresult.getText());
            sb.deleteCharAt(tresult.getText().length()-1);
            tresult.setText(sb.toString());
        }
    }//GEN-LAST:event_btnbsActionPerformed

    private void bbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnplusActionPerformed
       num1 = Double.parseDouble(tresult.getText());
        tresult.setText(null);
        op = "+";
    }//GEN-LAST:event_bbtnplusActionPerformed

    private void bbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtndotActionPerformed
        enteredval(".");// TODO add your handling code here:
    }//GEN-LAST:event_bbtndotActionPerformed

    private void bbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtn1ActionPerformed
        enteredval("1");// TODO add your handling code here:
    }//GEN-LAST:event_bbtn1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbtn0;
    private javax.swing.JButton bbtn1;
    private javax.swing.JButton bbtn2;
    private javax.swing.JButton bbtn3;
    private javax.swing.JButton bbtn4;
    private javax.swing.JButton bbtn5;
    private javax.swing.JButton bbtn6;
    private javax.swing.JButton bbtn7;
    private javax.swing.JButton bbtn8;
    private javax.swing.JButton bbtn9;
    private javax.swing.JButton bbtnclear;
    private javax.swing.JButton bbtndivide;
    private javax.swing.JButton bbtndot;
    private javax.swing.JButton bbtnequal;
    private javax.swing.JButton bbtnminus;
    private javax.swing.JButton bbtnmultiply;
    private javax.swing.JButton bbtnplus;
    private javax.swing.JButton bbtnsign;
    private javax.swing.JButton btnbs;
    private javax.swing.JTextField tresult;
    // End of variables declaration//GEN-END:variables
}
